# Generated by Django 6.0.3 on 2026-03-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
